#! /bin/bash

pushd "$( dirname "${BASH_SOURCE[0]}" )" >> /dev/null
for game in *.ts; do
    if [[ $game == "base.ts" ]]; then
        continue
    fi

    file=$(echo $game | rev | cut -c 4- | rev)
    echo -n "Compiling $file into /client/games/$file.js..."
    tsc --out ../../client/games/$file.js $file.ts || break
    echo "Done"
done

#cp ../../bower_components/phaser/build/phaser.js ../../public/js/compiled/lib/phaser.js
popd >> /dev/null
